### ISSUE TITLE
Error occurs when running the net_segment

### ISSUE THREAD

**Issue by Fei-Xia-oe** [soltanianzadeh/STNeuroNet#8]
I am running the net_segment inference after installing everything. But got the error below. Can you help debug? Also, I am a bit confused on how to use the model to retrain my own data set. Do you have a more detailed to do list for this purpose?
(stneuronet) C:\Users\XX\Anaconda3>net_segment inference -c C:\Users\XX\STNeuroNet-master\config_neuro.ini
NiftyNet version 0.2.0.post1
CRITICAL:tensorflow:could not create model folder:
Traceback (most recent call last):
  File "c:\users\fei\anaconda3\envs\stneuronet\lib\site-packages\niftynet\io\misc_io.py", line 336, in touch_folder
    os.makedirs(model_dir)
  File "c:\users\fei\anaconda3\envs\stneuronet\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\fei\anaconda3\envs\stneuronet\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\fei\anaconda3\envs\stneuronet\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Fei\Anaconda3\envs\stneuronet\Scripts\net_segment.exe\__main__.py", line 9, in <module>
  File "c:\users\fei\anaconda3\envs\stneuronet\lib\site-packages\niftynet\__init__.py", line 42, in main
    model_folder = touch_folder(system_param['SYSTEM'].model_dir)
  File "c:\users\fei\anaconda3\envs\stneuronet\lib\site-packages\niftynet\io\misc_io.py", line 339, in touch_folder
    raise OSError
OSError

**Comment by soltanianzadeh** [comment]
@emilyxia I'm guessing the `model_dir` in your configuration file is not valid. It looks like you are running `net_segment` from a different directory than where `config_neuro.ini` is located. Make sure the `model_dir` you've typed in is pointing to the correct location. Specifically, have you used relative path or absolute path? If you are using relative path, the program will try to look for the folder **relative to where you are running the code**. In your case, it will be relative to `C:\Users\XX\Anaconda3`.


As for retraining, specify `model_dir` to point to the location of the model weights you want to continue the training from. You would also need to specify `starting_iter` in the configuration file to, for example, 35999 (the iteration number you are trying to continue from).

Hope these explanations help.
